version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/com.examples.hellodocker"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
